# Generated by Django 5.1.2 on 2025-04-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
