# Generated by Django 5.1.2 on 2025-04-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_cart_user_slider"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="zip_file",
            field=models.FileField(blank=True, null=True, upload_to="slider_zips/"),
        ),
    ]
