# Generated by Django 5.1.2 on 2025-04-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_slider_zip_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="slider",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="slider_images/"),
        ),
    ]
