# Generated by Django 5.1.2 on 2025-04-25 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_cart_cart_id_alter_cart_user_alter_cartitem_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slider",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="slider",
            name="zip_file",
        ),
        migrations.AddField(
            model_name="slider",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="slider",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="slider",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=models.ImageField(null=True, upload_to="sliders/"),
        ),
        migrations.AlterField(
            model_name="slider",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.product",
            ),
        ),
        migrations.AlterField(
            model_name="slider",
            name="text",
            field=models.CharField(max_length=255),
        ),
    ]
