# Generated by Django 5.1.2 on 2025-04-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_remove_slider_is_active_remove_slider_zip_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
