# Generated by Django 5.1.2 on 2025-04-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="top_deals/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
